---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- My First Group:
    - Proxmox Server:
        href: http://192.168.1.130
        description: Proxmox Server
        icon: ../png/proxmox.png

    - My First Service:
        href: http://localhost/
        description: Testing Proxmox
        icon: ../png/proxmox.png

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
